export const ADD_INGREDIANT = "ADD_INGREDIANT";
export const REMOVE_INGREDIANT = "REMOVE_INGREDIANT";
export const SET_INGREDIANTS = "SET_INGREDIANTS";
export const INIT_INGREDIANTS = "INIT_INGREDIANTS";
export const FETCH_INGREDIANTS_FAILED = "FETCH_INGREDIANTS_FAILED";

export const PURCHASE_BURGER = "PURCHASE_BURGER";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_CHECK_INITIAL_STATE = "AUTH_CHECK_INITIAL_STATE";
export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CHECK_TIME = "AUTH_CHECK_TIME";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
